"""Export chat sessions as DOCX documents."""

import io
from datetime import datetime

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def session_to_docx(session) -> bytes:
    """Convert a chat session to a DOCX document and return bytes."""
    doc = Document()

    # Style setup
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Title
    title = doc.add_heading(session.title or "Chat Session", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta.add_run(f"Exported from Étude on {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph("")  # Spacer

    # Messages
    for msg in session.messages:
        if msg.role == "user":
            heading = doc.add_heading("You", level=3)
            heading_run = heading.runs[0]
            heading_run.font.color.rgb = RGBColor(0, 0, 0)

            if msg.file:
                file_para = doc.add_paragraph()
                file_run = file_para.add_run(f"[Attached: {msg.file.filename}]")
                file_run.font.size = Pt(9)
                file_run.font.color.rgb = RGBColor(100, 100, 100)
                file_run.italic = True

            doc.add_paragraph(msg.content)

        elif msg.role == "assistant":
            label = msg.model_name or "Assistant"
            heading = doc.add_heading(label, level=3)
            heading_run = heading.runs[0]
            heading_run.font.color.rgb = RGBColor(26, 92, 92)  # Teal

            # Split content into paragraphs for better formatting
            for para_text in msg.content.split("\n\n"):
                if para_text.strip():
                    doc.add_paragraph(para_text.strip())

        # Separator
        sep = doc.add_paragraph()
        sep_run = sep.add_run("─" * 50)
        sep_run.font.size = Pt(8)
        sep_run.font.color.rgb = RGBColor(200, 200, 200)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Generated by Étude — Powered by Anthropic Claude models")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)

    # Write to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def message_to_docx(markdown_content: str, title: str = None) -> bytes:
    """Convert a single message's markdown content to a DOCX document."""
    import re

    doc = Document()

    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Try to extract title from first heading
    heading_match = re.match(r'^#+ (.+)', markdown_content, re.MULTILINE)
    doc_title = heading_match.group(1) if heading_match else (title or "Document")

    heading = doc.add_heading(doc_title, level=1)
    heading.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Split content into paragraphs and add them
    # Skip the first heading if we already used it as title
    lines = markdown_content.strip().split('\n')
    skip_first_heading = heading_match is not None
    content_started = False

    for line in lines:
        stripped = line.strip()

        # Skip the first heading since we used it as title
        if skip_first_heading and not content_started and re.match(r'^#+ ', stripped):
            content_started = True
            continue

        content_started = True

        if not stripped:
            continue

        # Handle headings
        heading_m = re.match(r'^(#{1,4})\s+(.+)', stripped)
        if heading_m:
            level = min(len(heading_m.group(1)), 4)
            doc.add_heading(heading_m.group(2), level=level)
            continue

        # Handle horizontal rules
        if re.match(r'^(-{3,}|_{3,}|\*{3,})$', stripped):
            sep = doc.add_paragraph()
            sep_run = sep.add_run("─" * 50)
            sep_run.font.size = Pt(8)
            sep_run.font.color.rgb = RGBColor(200, 200, 200)
            continue

        # Handle bullet points
        if stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
            continue

        # Handle numbered lists
        num_m = re.match(r'^\d+\.\s+(.+)', stripped)
        if num_m:
            doc.add_paragraph(num_m.group(1), style='List Number')
            continue

        # Regular paragraph — strip basic markdown formatting
        text = stripped
        text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # bold
        text = re.sub(r'\*(.+?)\*', r'\1', text)  # italic
        text = re.sub(r'`(.+?)`', r'\1', text)  # inline code
        doc.add_paragraph(text)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("Generated by Étude")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
