"""Service for exporting session data in various formats."""

import json
from typing import List

from core.timestamps import utc_iso
from schemas import ChatSession


def format_as_json(sessions: List[ChatSession]) -> str:
    """Format sessions as JSON."""
    sessions_data = [session.model_dump() for session in sessions]
    export_data = {
        "export_date": utc_iso(),
        "session_count": len(sessions),
        "sessions": sessions_data,
    }
    return json.dumps(export_data, indent=2, ensure_ascii=False)


def format_as_markdown(sessions: List[ChatSession]) -> str:
    """Format sessions as Markdown."""
    lines = [
        "# Chat Export",
        "",
        f"**Export Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
        f"**Total Sessions:** {len(sessions)}",
        "",
        "---",
        "",
    ]

    for idx, session in enumerate(sessions, 1):
        lines.append(f"## Session {idx}: {session.title or 'Untitled'}")
        lines.append("")
        lines.append(f"**Session ID:** `{session.id}`")

        if session.is_pinned:
            lines.append("**Status:** Pinned")

        messages = session.messages if hasattr(session, 'messages') else []
        lines.append(f"**Messages:** {len(messages)}")
        lines.append("")

        for msg in messages:
            if msg.role == "user":
                lines.append(f"### You")
            else:
                label = msg.model_name or "Assistant"
                lines.append(f"### {label}")
            lines.append("")
            lines.append(msg.content)
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("")
    lines.append("*Generated by Étude*")

    return "\n".join(lines)
